Unit dimerpc;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file:dime-rpc.wsdl
Date:     7/7/2003 17:20:16
IndySoap: V1.00
---------------------------------------------------------------------------}

Interface

Uses
  Classes,
  IdSoapClient,
  IdSoapTypeRegistry;

Type
  TReferencedBinary = type TIdSoapAttachment;
  TReferencedText = type TIdSoapAttachment;

  TArrayOfBinary = array of TReferencedBinary;

{!
  Name: In_ = In;
  Name: Out_ = Out;
  Type: TArrayOfBinary = ArrayOfBinary in http://soapinterop.org/attachments/xsd;
  Type: TReferencedBinary = ReferencedBinary in http://soapinterop.org/attachments/xsd;
  Type: TReferencedText = ReferencedText in http://soapinterop.org/attachments/xsd;
}

type
  {Soap Address for this Interface: http://localhost/test}
  IAttTest = Interface (IIdSoapInterface) ['{532A2F2D-E561-4A22-8756-E6BCA733FA14}']
       {!Namespace: http://soapinterop.org/attachments/;
         SoapAction: http://soapinterop.org/attachments/;
         Attachments: Dime}
    procedure EchoAttachment(In_ : TReferencedBinary; out Out_ : TReferencedBinary); stdcall;
    procedure EchoAttachments(In_ : TArrayOfBinary; out Out_ : TArrayOfBinary); stdcall;
    procedure EchoAttachmentAsBase64(In_ : TReferencedBinary; out Out_ : TStream); stdcall;
    procedure EchoBase64AsAttachment(In_ : TStream; out Out_ : TReferencedBinary); stdcall;
    procedure EchoUnrefAttachments; stdcall;
    procedure EchoAttachmentAsString(In_ : TReferencedText; out Out_ : String); stdcall;
  end;

function GetIAttTest(AClient : TIdSoapBaseSender; ASetUrl : Boolean = true) : IAttTest;

Implementation

{$R dimerpc.res}

Uses
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;


function GetIAttTest(AClient : TIdSoapBaseSender; ASetUrl : Boolean = true) : IAttTest;
begin
  if ASetURL and (AClient is TIdSoapWebClient) then
    begin
    (AClient as TIdSoapWebClient).SoapURL := 'http://localhost/test';
    end;
  result := IdSoapD4Interface(AClient) as IAttTest;
end;

Initialization
  IdSoapRegisterType(TypeInfo(TArrayOfBinary), '', TypeInfo(TReferencedBinary));
  IdSoapRegisterType(TypeInfo(TReferencedBinary));
  IdSoapRegisterType(TypeInfo(TReferencedText));
End.
