Unit Interop;

{---------------------------------------------------------------------------
This file generated by the IndySoap WSDL -> Pascal translator

Source:   file://SoapBuilders\Interop.wsdl
Date:     29/10/2002 10:06:56
IndySoap: V0.04
---------------------------------------------------------------------------}

Interface

Uses
  Classes,
  IdSoapClient,
  IdSoapDateTime,
  IdSoapTypeRegistry;

Type

  SOAPStruct = class;

  ArrayOfSOAPStruct = array of SOAPStruct;
  ArrayOffloat = array of Single;
  ArrayOfint = array of Integer;
  ArrayOfstring = array of String;

  SOAPStruct = class (TIdBaseSoapableClass)
  Private
    FvarString : String;
    FvarInt : Integer;
    FvarFloat : Single;
  Published
    property varString : String read FvarString write FvarString;
    property varInt : Integer read FvarInt write FvarInt;
    property varFloat : Single read FvarFloat write FvarFloat;
  end;


  {Soap Address for this Interface: http://localhost/soap/}
  InteropTest = Interface (IIdSoapInterface) ['{1B49E85A-2F53-4FBB-975A-AF6D56D29EB6}']
       {!Namespace: http://soapinterop.org/;
         Type: ArrayOffloat = in http://soapinterop.org/xsd;
         Type: ArrayOfint = in http://soapinterop.org/xsd;
         Type: ArrayOfSOAPStruct = in http://soapinterop.org/xsd;
         Type: ArrayOfstring = in http://soapinterop.org/xsd;
         Type: SOAPStruct = in http://soapinterop.org/xsd}
    function  echoString(inputString : String) : String; stdcall;
    function  echoStringArray(inputStringArray : ArrayOfstring) : ArrayOfstring; stdcall;
    function  echoInteger(inputInteger : Integer) : Integer; stdcall;
    function  echoIntegerArray(inputIntegerArray : ArrayOfint) : ArrayOfint; stdcall;
    function  echoFloat(inputFloat : Single) : Single; stdcall;
    function  echoFloatArray(inputFloatArray : ArrayOffloat) : ArrayOffloat; stdcall;
    function  echoStruct(inputStruct : SOAPStruct) : SOAPStruct; stdcall;
    function  echoStructArray(inputStructArray : ArrayOfSOAPStruct) : ArrayOfSOAPStruct; stdcall;
    procedure echoVoid; stdcall;
    function  echoBase64(inputBase64 : TStream) : TStream; stdcall;
    function  echoDate(inputDate : TIdSoapDateTime) : TIdSoapDateTime; stdcall;
  end;

function GetInteropTest(AClient : TIdSoapBaseSender) : InteropTest;

Implementation

uses
  IdSoapRTTIHelpers,
  IdSoapUtilities,
  SysUtils;



function GetInteropTest(AClient : TIdSoapBaseSender) : InteropTest;
begin
  result := IdSoapD4Interface(AClient) as InteropTest;
end;

Initialization
  IdSoapRegisterType(TypeInfo(ArrayOfSOAPStruct), '', TypeInfo(SOAPStruct));
  IdSoapRegisterType(TypeInfo(SOAPStruct));
  IdSoapRegisterType(TypeInfo(ArrayOffloat), '', TypeInfo(Single));
  IdSoapRegisterType(TypeInfo(ArrayOfint), '', TypeInfo(Integer));
  IdSoapRegisterType(TypeInfo(ArrayOfstring), '', TypeInfo(String));
End.
